#define GPIO_MODE 22
#define GPIO_ADDRESS_0 14
#define GPIO_ADDRESS_1 15
#define GPIO_ADDRESS_2 16
#define GPIO_ADDRESS_3 17
#define GPIO_ADDRESS_4 18
#define GPIO_ADDRESS_5 19
#define GPIO_ADDRESS_6 20
#define GPIO_ADDRESS_7 21
#define GPIO_ANALOG_1 A11
#define GPIO_ANALOG_2 A10
#define GPIO_ANALOG_3 A9
#define GPIO_ANALOG_4 A14
#define GPIO_SWITCH_1 12
#define GPIO_SWITCH_2 11
#define GPIO_SWITCH_3 10
#define GPIO_SWITCH_4 9
#define GPIO_SWITCH_5 8
#define GPIO_SWITCH_6 7
#define GPIO_RELAY_1 6
#define GPIO_RELAY_2 5
#define GPIO_RELAY_3 1
#define GPIO_RELAY_4 0
#define GPIO_BOARD_LED 13
#define GPIO_LED_1 2

#define GPIO_PUSH_1 GPIO_SWITCH_5
#define GPIO_PUSH_2 GPIO_SWITCH_6


#define GPIO_DIGITAL_INPUT_PINS { GPIO_MODE, GPIO_ADDRESS_0, GPIO_ADDRESS_1, GPIO_ADDRESS_2, GPIO_ADDRESS_3, GPIO_ADDRESS_4, GPIO_ADDRESS_5, GPIO_ADDRESS_6, GPIO_ADDRESS_7, GPIO_SWITCH_1, GPIO_SWITCH_2, GPIO_SWITCH_3, GPIO_SWITCH_4, GPIO_SWITCH_5, GPIO_SWITCH_6 }
#define GPIO_DIGITAL_OUTPUT_PINS { GPIO_RELAY_1, GPIO_RELAY_2, GPIO_RELAY_3, GPIO_RELAY_4, GPIO_BOARD_LED, GPIO_LED_1 }
#define GPIO_ADDRESS_PINS { GPIO_ADDRESS_0, GPIO_ADDRESS_1, GPIO_ADDRESS_2, GPIO_ADDRESS_3, GPIO_ADDRESS_4, GPIO_ADDRESS_5, GPIO_ADDRESS_6, GPIO_ADDRESS_7 }
#define GPIO_ANALOG_PINS { GPIO_ANALOG_1, GPIO_ANALOG_2, GPIO_ANALOG_3, GPIO_ANALOG_4 }